// <auto-generated />
using System;
using LAPTOP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAPTOP.Migrations
{
    [DbContext(typeof(STORELAPTOPContext))]
    [Migration("20251124123333_FixFinalVarCharColumns")]
    partial class FixFinalVarCharColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LAPTOP.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<string>("MaSp")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaSp")
                        .HasName("PK__ChiTietH__F557F661D651EF0C");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.ChiTietSanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<string>("Cpu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CPU");

                    b.Property<string>("HeDieuHanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ManHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ram")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RAM");

                    b.Property<string>("Vga")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VGA");

                    b.HasKey("MaSp")
                        .HasName("PK__ChiTietS__2725081C6CDEC7DD");

                    b.ToTable("ChiTietSanPham", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<string>("MaKh")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("MaNv")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("date");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0F36B725F");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E3F3DD519");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_KhachHang_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<decimal?>("HeSoLuong")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenNv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNV");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A8F9AB923");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081CA3079783");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("LAPTOP.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("LAPTOP.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaHD__440B1D61");

                    b.HasOne("LAPTOP.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHoa__MaSP__44FF419A");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("LAPTOP.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("LAPTOP.Models.SanPham", "MaSpNavigation")
                        .WithOne("ChiTietSanPham")
                        .HasForeignKey("LAPTOP.Models.ChiTietSanPham", "MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietSan__MaSP__3D5E1FD2");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("LAPTOP.Models.HoaDon", b =>
                {
                    b.HasOne("LAPTOP.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__HoaDon__MaKH__412EB0B6");

                    b.HasOne("LAPTOP.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__HoaDon__MaNV__403A8C7D");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("LAPTOP.Models.SanPham", b =>
                {
                    b.HasOne("LAPTOP.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("LAPTOP.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("LAPTOP.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("LAPTOP.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("LAPTOP.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("LAPTOP.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
